### ISSUE TITLE
Trying to use postgres instead of H2

### ISSUE THREAD

**Issue by SyedIlyasAtIntBitTech** [rajithd/spring-boot-oauth2#4]
Hi Rajithd,

For one of projects am working on i need to do the backend with postgresql and do oauth2. I am trying to converting your project to postgres from h2.

Wonder if you can help out?

Have you written anything for postgres + spring boot + oauth2?

**Comment by rajithd** [comment]
hi @SyedIlyasAtIntBitTech 
I think you don't need to do much conversion. Because I convert this project to use mysql and comparing with postgresql its just the configuration. 

What you need to do is just to change the configs in application.properties and it should good to go. Here is the changes that I did for mysql.
```java
spring.datasource.url=jdbc:mysql://localhost:3306/<db_name>?useUnicode=true&characterEncoding=utf-8
spring.datasource.username=<db_username>
spring.datasource.password=<db_password>
spring.datasource.dataSourceClassName=com.mysql.jdbc.Driver
spring.datasource.schema=classpath:/sql/schema.sql
spring.datasource.data=classpath:/sql/data.sql

spring.jpa.database=MYSQL
spring.jpa.show_sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
```

**Comment by SyedIlyasAtIntBitTech** [comment]
Hey,

Thanks for that, it does work with postgresql as you said.

Appreciate the quick response.
